# Docker


# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
      - task: Docker@2
        inputs:
          containerRegistry: 'Google Container Registry'
          repository: 'sit-sandbox7-sb/hello-kubernetes'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest
      - task: CopyFiles@2
        inputs:
          SourceFolder: './yaml/'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/yaml/'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'